FROM maven:3.9-eclipse-temurin-17-alpine AS builder
WORKDIR /app


COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests -f pom.xml

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

COPY --from=builder /app/target/*.jar app.jar

HEALTHCHECK --interval=30s --timeout=3s --start-period=60s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1

EXPOSE 8888

ENTRYPOINT ["java", "-jar", "app.jar"]